### ISSUE TITLE
Apply: Deactivated Apply Link Page

### ISSUE THREAD

**Issue by mcsuehiro** [rentapplication/themes#112]
A page needs to be created for an application link that has been deactivated

Refer to Zeplin screens "deactivated-apply-link" and "deactivated-apply-link (m)" for full details

![deactivated-apply-link](https://cloud.githubusercontent.com/assets/18620601/23440622/918b72a2-fde2-11e6-9c7c-daf695d00718.png)

**Comment by ezl** [comment]
@mcsuehiro 
request for updated copy "emailing them at... " + phone number seems a bit awkward.

how about either:

1. just "contacting them at..." then email+phone or
2. remove phone number

**Comment by mcsuehiro** [comment]
@ezl  text change has been updated 👍
