### ISSUE TITLE
Apply-Application: Email/Website Overflow popup- change font size

### ISSUE THREAD

**Issue by mcsuehiro** [rentapplication/themes#120]

**Comment by Ihorpryt** [comment]
which one font, and what font size?

**Comment by mcsuehiro** [comment]
Oops! Change font size of text in pop up to 14px
![project title 2017-04-06 10-03-24](https://cloud.githubusercontent.com/assets/18620601/24804735/1bcd4dbe-1b75-11e7-8826-10ec73d1cf11.png)
