### ISSUE TITLE
Apply-Application: digital signature interaction/modal (div.sign)

### ISSUE THREAD

**Issue by mcsuehiro** [rentapplication/themes#37]
the digital signature input triggers a 'signature' modal; here is a video of the intended interaction: https://monosnap.com/file/BazfwFIpxUZXHhG30hupYhXURJ8Ji6

to see a live version of the input you can also go to: https://www.rentapplication.net/yp95Lc/
(the signature input is at the bottom of the page)

The details for the signature modal styling are uploaded in Zeplin as 'Signature' and 'Signature (m)'

**Comment by ezl** [comment]
@Ihorpryt @mcsuehiro for the purposes of the `themes` repository code, no need to try to make the signing actually work -- just make it so that when clicking on the inline signature representation in the form, the actual signature box appears as misaki has designed it.
